### ISSUE TITLE
Backwards Incompatible Change in 0.5.1

### ISSUE THREAD

**Issue by BeatButton** [pacman82/odbc-safe#16]
Version 0.5.1 includes the commit https://github.com/pacman82/odbc-safe/commit/366d5c2551841d8722b1b5a989cc333351b3de86, which breaks, for example, odbc-rs, by adding type constraints that were not previously required.

**Comment by pacman82** [comment]
Hello @BeatButton , thanks for taking the time to help others avoiding pain during `cargo update`, even if it means contributing to a deprecated crate. So I woder what is the nice thing todo here? I've seen your request in `odbc-rs` and IMHO it is probably the way to go. An alternative could also be to yank 0.5.1 and rerelease it as 0.6.0.

**Comment by BeatButton** [comment]
I think strictly there should be a version bump due to the backwards-incompatible nature of the change.

odbc-rs does appear to account for 95% of the indirect dependencies on this crate, even though the change does break r2d2_odbc and ibm_db, the other two public dependent crates.

So, the PR being accepted over there would solve most of the problem, excluding any private crates that depend directly on this one. Of course, there's no guarantee that the PR over there _will_ be accepted.

**Comment by pacman82** [comment]
Even if `odbc-rs` would accept the change it should release it with a breaking version number. So users just running `cargo update` woud still get a broken build. IMHO best thing to do: Patch release of `odbc-rs` with pinned version number for `odbc-safe`.

**Comment by pacman82** [comment]
Yanked `0.5.1` and rereleased as `0.6.0`. This should remove some of the pain, but not all.
